/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PointOfSale;

import Authentication.LoginFrame;
import Authentication.User;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author britt
 */
public class POSFrame extends javax.swing.JFrame {

    POS pos;//update
    ArrayList<String> discountCodes;
    private User employee;

    /**
     * Creates new form POSFrame
     */
    public POSFrame(User user) {
        initComponents();
        this.employee = user;
        pos = new POS(user);
        customerIdTxt.setText(String.valueOf(pos.getCurrentCustomer().getId()));
        discountCodes = new ArrayList<>();
        DateTime();
        loadPyamentDropDown();
        employeeIdLabel.setText(String.valueOf(user.getId()));
        greetLabel.setText("Hello " + user.getFirstname() + ",");
    }
    
    private void updateOrdersTable() {
        DefaultTableModel model = (DefaultTableModel) ordersTable.getModel();
        model.setRowCount(0);

        try {
            for (Transaction transaction : pos.getPendingTransactions()) {
                Object[] rowData = {
                    transaction.getTransactionId()
                };
                //System.out.println(product.getName());
                model.addRow(rowData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateItemsTable(ArrayList<TransactionItem> items) {
        DefaultTableModel model = (DefaultTableModel) itemsTable.getModel();
        model.setRowCount(0);
        String discCode;
        double discAmt;  
        
        try {
            for (TransactionItem item : items) {
                discCode = "";
                discAmt = 0.0;
                if (item.getDiscount() != null){
                    discCode = item.getDiscount().getCode();
                    discAmt = item.getDiscount().getAmount();
                }
                Object[] rowData = {
                    item.getProductId(),
                    item.getQuantity(),
                    item.getPrice(),
                    item.getTotal(),
                    discCode,
                    discAmt                    
                };
                //System.out.println(product.getName());
                model.addRow(rowData);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void loadPyamentDropDown() {
        ArrayList<PaymentType> paymentTypes = pos.getPaymentTypes();
        ArrayList<String> names = new ArrayList<String>();
        for (PaymentType paymentType : paymentTypes) {
            names.add(paymentType.getName());
        }
        paymentField.setModel(new javax.swing.DefaultComboBoxModel<>(names.toArray(new String[0])));
    }
    public void updateTotal() {
        DefaultTableModel model = (DefaultTableModel) ordersTable.getModel();
        int selectedRowIndex = ordersTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            int orderId = (int) model.getValueAt(selectedRowIndex, 0);
            Transaction order = pos.getPendingTransactionByID(orderId);
            discountCodes = pos.applyAllDiscount(order, discountCodes);
            NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(Locale.US);
            totalTxt.setText(currencyFormatter.format(order.getTotal()));
            taxTxt.setText(currencyFormatter.format(order.getTotal() * 1.15));
            updateOrdersTable();
            updateItemsTable(order.getItems());

        } else {
            JOptionPane.showMessageDialog(null, "Please select an order.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void DateTime(){
        LocalDateTime dt = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("EEEE, MMMM dd, yyyy");
        String formattedDate = dt.format(formatter);
        dateTime.setText(formattedDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        employeeIdLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateTime = new javax.swing.JLabel();
        greetLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        addOrderBtn = new javax.swing.JButton();
        removeOrderBtn = new javax.swing.JButton();
        itemItemLabel = new javax.swing.JLabel();
        itemIDField = new javax.swing.JTextField();
        itemQuantityLabel = new javax.swing.JLabel();
        itemQuantityField = new javax.swing.JTextField();
        removeItemBtn = new javax.swing.JButton();
        addItemBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JLabel();
        completeOrderBtn = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        redeemPointsBtn = new javax.swing.JButton();
        discCodeTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        applyDiscBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerIdTxt = new javax.swing.JTextPane();
        pointsToRedeemTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        amtGivenTxt = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        changeTxt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        totalTxt1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        taxTxt = new javax.swing.JLabel();
        paymentBtn = new javax.swing.JButton();
        printReceiptBtn = new javax.swing.JButton();
        allPointsTxt = new javax.swing.JLabel();
        paymentField = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1442, 800));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 32)); // NOI18N
        jLabel1.setText("Point of Sale");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel4.setText("Copyright © 2024 Sales Amigo");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Staff ID:");

        employeeIdLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        employeeIdLabel.setText(" ");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setText("Date:");

        dateTime.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dateTime.setText(" ");

        greetLabel.setFont(new java.awt.Font("Helvetica Neue", 2, 21)); // NOI18N
        greetLabel.setText(" ");

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Order ID #"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(ordersTable);
        if (ordersTable.getColumnModel().getColumnCount() > 0) {
            ordersTable.getColumnModel().getColumn(0).setResizable(false);
        }

        addOrderBtn.setBackground(new java.awt.Color(51, 102, 255));
        addOrderBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        addOrderBtn.setText("Add New Order");
        addOrderBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addOrderBtn.setOpaque(true);
        addOrderBtn.setPreferredSize(new java.awt.Dimension(133, 24));
        addOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderBtnActionPerformed(evt);
            }
        });

        removeOrderBtn.setBackground(new java.awt.Color(204, 0, 51));
        removeOrderBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        removeOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeOrderBtn.setText("Remove Order");
        removeOrderBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeOrderBtn.setOpaque(true);
        removeOrderBtn.setPreferredSize(new java.awt.Dimension(133, 24));
        removeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeOrderBtnActionPerformed(evt);
            }
        });

        itemItemLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        itemItemLabel.setText("Item ID");

        itemIDField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        itemIDField.setText("Item ID");
        itemIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIDFieldActionPerformed(evt);
            }
        });

        itemQuantityLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        itemQuantityLabel.setText("Quantity");

        itemQuantityField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        itemQuantityField.setText("1");
        itemQuantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQuantityFieldActionPerformed(evt);
            }
        });

        removeItemBtn.setBackground(new java.awt.Color(204, 0, 51));
        removeItemBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        removeItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeItemBtn.setText("Remove Item");
        removeItemBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeItemBtn.setOpaque(true);
        removeItemBtn.setPreferredSize(new java.awt.Dimension(133, 24));
        removeItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemBtnActionPerformed(evt);
            }
        });

        addItemBtn.setBackground(new java.awt.Color(51, 102, 255));
        addItemBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        addItemBtn.setText("Add Item");
        addItemBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addItemBtn.setOpaque(true);
        addItemBtn.setPreferredSize(new java.awt.Dimension(133, 24));
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 19)); // NOI18N
        jLabel13.setText("Items for Checkout");

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item Name", "Quantity", "Price Per Unit", "Total", "Discount Code", "Discount Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(itemsTable);
        if (itemsTable.getColumnModel().getColumnCount() > 0) {
            itemsTable.getColumnModel().getColumn(0).setResizable(false);
            itemsTable.getColumnModel().getColumn(1).setResizable(false);
            itemsTable.getColumnModel().getColumn(2).setResizable(false);
            itemsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 19)); // NOI18N
        jLabel6.setText("Order ID #");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 19)); // NOI18N
        jLabel7.setText("Add Item");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(greetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(addOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(removeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(removeItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemQuantityLabel)
                                    .addComponent(itemItemLabel))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(dateTime)
                    .addComponent(employeeIdLabel))
                .addGap(18, 18, 18)
                .addComponent(greetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemItemLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemQuantityLabel))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Quantity");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setOpaque(true);
        jButton2.setPreferredSize(new java.awt.Dimension(133, 24));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        jLabel2.setText("TOTAL:");

        totalTxt.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        totalTxt.setText("$0.00");

        completeOrderBtn.setBackground(new java.awt.Color(0, 102, 102));
        completeOrderBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        completeOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        completeOrderBtn.setText("COMPLETE ORDER");
        completeOrderBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        completeOrderBtn.setOpaque(true);
        completeOrderBtn.setPreferredSize(new java.awt.Dimension(133, 24));
        completeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeOrderBtnActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 102, 0));
        jButton8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Discount Code");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setOpaque(true);
        jButton8.setPreferredSize(new java.awt.Dimension(133, 24));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        redeemPointsBtn.setBackground(new java.awt.Color(204, 102, 0));
        redeemPointsBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        redeemPointsBtn.setForeground(new java.awt.Color(255, 255, 255));
        redeemPointsBtn.setText("Redeem Points");
        redeemPointsBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        redeemPointsBtn.setOpaque(true);
        redeemPointsBtn.setPreferredSize(new java.awt.Dimension(133, 24));
        redeemPointsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redeemPointsBtnActionPerformed(evt);
            }
        });

        discCodeTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        discCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discCodeTxtActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setText("Customer ID:");

        jTextPane1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel14.setText("Points:");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel15.setText("Payment Method:");

        applyDiscBtn.setBackground(new java.awt.Color(51, 102, 255));
        applyDiscBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        applyDiscBtn.setForeground(new java.awt.Color(255, 255, 255));
        applyDiscBtn.setText("Apply Points");
        applyDiscBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        applyDiscBtn.setOpaque(true);
        applyDiscBtn.setPreferredSize(new java.awt.Dimension(133, 24));
        applyDiscBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyDiscBtnActionPerformed(evt);
            }
        });

        customerIdTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jScrollPane3.setViewportView(customerIdTxt);

        pointsToRedeemTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        pointsToRedeemTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsToRedeemTxtActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel16.setText("Amount Given:");

        amtGivenTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jScrollPane5.setViewportView(amtGivenTxt);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        jLabel10.setText("Change due:");

        changeTxt.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        changeTxt.setText("$0.00");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        jLabel12.setText("Sub TOTAL:");

        totalTxt1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        totalTxt1.setText("$0.00");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        jLabel17.setText("Tax:");

        taxTxt.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        taxTxt.setText("$0.00");

        paymentBtn.setBackground(new java.awt.Color(0, 153, 0));
        paymentBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        paymentBtn.setForeground(new java.awt.Color(255, 255, 255));
        paymentBtn.setText("Enter Payment");
        paymentBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paymentBtn.setOpaque(true);
        paymentBtn.setPreferredSize(new java.awt.Dimension(133, 24));
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });

        printReceiptBtn.setBackground(new java.awt.Color(0, 102, 102));
        printReceiptBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        printReceiptBtn.setForeground(new java.awt.Color(255, 255, 255));
        printReceiptBtn.setText("Print Receipt");
        printReceiptBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        printReceiptBtn.setOpaque(true);
        printReceiptBtn.setPreferredSize(new java.awt.Dimension(133, 24));
        printReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReceiptBtnActionPerformed(evt);
            }
        });

        allPointsTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        allPointsTxt.setText("All Points");
        allPointsTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allPointsTxtMouseClicked(evt);
            }
        });

        paymentField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        paymentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(redeemPointsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(discCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(pointsToRedeemTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(completeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(printReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(totalTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(changeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(18, 18, 18)
                                                .addComponent(taxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 34, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(paymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(applyDiscBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(65, 65, 65))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(allPointsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redeemPointsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pointsToRedeemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(allPointsTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(applyDiscBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(paymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(changeTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(totalTxt1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(taxTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(completeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTxt)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(187, 67));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sales Amigo");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salesamigo-logo.png"))); // NOI18N

        jButton6.setBackground(new java.awt.Color(51, 102, 255));
        jButton6.setFont(new java.awt.Font("Helvetica Neue", 1, 19)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Logout");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton6)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(618, 618, 618)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(623, 623, 623)
                        .addComponent(jLabel1)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderBtnActionPerformed
        // TODO add your handling code here:
        pos.createSaleTransaction(1, 1);
        updateOrdersTable();
    }//GEN-LAST:event_addOrderBtnActionPerformed

    private void removeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeOrderBtnActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) ordersTable.getModel();
        int selectedRowIndex = ordersTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            int orderId = (int) model.getValueAt(selectedRowIndex, 0);
            Transaction pendingTransaction = pos.getPendingTransactionByID(orderId);
            String message = String.format("Order Deletion:\nOrder ID: %d\n", orderId);

            int option = JOptionPane.showConfirmDialog(this, message + "\nAre you sure you want to order variant with ID: " + orderId + "?", "Delete Product", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                //String feedback = inventory.deleteVariant(variant_id);
                //JOptionPane.showMessageDialog(this, feedback, "Variant Deleted", JOptionPane.INFORMATION_MESSAGE);
                pos.getPendingTransactions().remove(pendingTransaction);
                updateOrdersTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an order to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeOrderBtnActionPerformed

    private void discCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discCodeTxtActionPerformed

    private void redeemPointsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redeemPointsBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ordersTable.getModel();
        int selectedRowIndex = ordersTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            int orderId = (int) model.getValueAt(selectedRowIndex, 0);
            Transaction pendingTransaction = pos.getPendingTransactionByID(orderId);
            if (!customerIdTxt.getText().equals("1") && !customerIdTxt.getText().equals("")) {
                int pointsToRedeem = Integer.parseInt(pointsToRedeemTxt.getText());
                //fix lol
                pos.setCustomer(Integer.parseInt(customerIdTxt.getText()));
                pendingTransaction.setCustomerId(Integer.parseInt(customerIdTxt.getText()));
                String message = String.format("Points Redemption:");

                int option = JOptionPane.showConfirmDialog(this, message + "\nAre you sure you want to redeem points?", "Redeem Points", JOptionPane.YES_NO_OPTION);

                if (option == JOptionPane.YES_OPTION) {
                    String feedback = pos.redeemPoints(orderId, pointsToRedeem);
                    JOptionPane.showMessageDialog(this, feedback, "Points Redeemed", JOptionPane.INFORMATION_MESSAGE);
                    NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(Locale.US);
                    totalTxt.setText(currencyFormatter.format(pendingTransaction.getTotal()));
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please enter a valid customer ID.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an order.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_redeemPointsBtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void completeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeOrderBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ordersTable.getModel();
        int selectedRowIndex = ordersTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            int orderId = (int) model.getValueAt(selectedRowIndex, 0);

            String message = String.format("Order Completion:\nProduct Name: %d\n", orderId);
            int option = JOptionPane.showConfirmDialog(this, message + "\nAre you sure you want to add this variant?", "Add New Variant", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                String feedback = pos.performSaleTransaction(orderId, "Cash");
                // Show details in another JOptionPane
                JOptionPane.showMessageDialog(this, feedback, "Variant Added", JOptionPane.INFORMATION_MESSAGE);
                updateOrdersTable();
                updateItemsTable(new ArrayList<>());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an order.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_completeOrderBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ordersTable.getModel();
        int selectedRowIndex = ordersTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            int orderId = (int) model.getValueAt(selectedRowIndex, 0);
            Transaction pendingTransaction = pos.getPendingTransactionByID(orderId);
//do check for invalid item id and stock levels
            int itemId = Integer.parseInt(itemIDField.getText());
            int quantity = Integer.parseInt(itemQuantityField.getText());
            double price = pos.getInventory().findVarantByID(itemId).getPrice();

            if (pendingTransaction.getItemByID(itemId) != null) {
                TransactionItem item = pendingTransaction.getItemByID(itemId);
                item.setQuantity(item.getQuantity() + quantity);
            } else {
                pendingTransaction.addTransactionItem(new TransactionItem(itemId, quantity, price));
            }
            pendingTransaction.calculateTotal();
            NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(Locale.US);
            totalTxt.setText(currencyFormatter.format(pendingTransaction.getTotal()));
            updateItemsTable(pendingTransaction.getItems());
        } else {
            JOptionPane.showMessageDialog(null, "Please select an order.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void removeItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel itemsModel = (DefaultTableModel) itemsTable.getModel();
        int selectedItem = itemsTable.getSelectedRow();

        DefaultTableModel ordersModel = (DefaultTableModel) ordersTable.getModel();
        int selectedOrder = ordersTable.getSelectedRow();

        if (selectedItem != -1 && selectedItem != -1) {
            int itemId = (int) itemsModel.getValueAt(selectedItem, 0);
            int orderId = (int) ordersModel.getValueAt(selectedOrder, 0);
            Transaction pendingTransaction = pos.getPendingTransactionByID(orderId);
            TransactionItem item = pendingTransaction.getItemByID(itemId);
            String message = String.format("Item Deletion:\nItem ID: %d\n", orderId);

            int option = JOptionPane.showConfirmDialog(this, message + "\nAre you sure you want to item with ID: " + itemId + "?", "Delete item", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                //String feedback = inventory.deleteVariant(variant_id);
                //JOptionPane.showMessageDialog(this, feedback, "Variant Deleted", JOptionPane.INFORMATION_MESSAGE);
                pendingTransaction.getItems().remove(item);
                updateItemsTable(pendingTransaction.getItems());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an item to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeItemBtnActionPerformed

    private void itemQuantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQuantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemQuantityFieldActionPerformed

    private void itemIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIDFieldActionPerformed

    private void applyDiscBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyDiscBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ordersTable.getModel();
        int selectedRowIndex = ordersTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            int orderId = (int) model.getValueAt(selectedRowIndex, 0);
            String discCode = discCodeTxt.getText();
            Transaction order = pos.getPendingTransactionByID(orderId);
            String feedback = pos.applyDiscount(order, discCode);
            if (!feedback.toLowerCase().contains("error")) {
                discountCodes.add(discCode);//update 
            }
            NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(Locale.US);
            totalTxt.setText(currencyFormatter.format(order.getTotal()));
            JOptionPane.showMessageDialog(this, feedback, "Discount", JOptionPane.INFORMATION_MESSAGE);
            updateOrdersTable();
            updateItemsTable(order.getItems());
        } else {
            JOptionPane.showMessageDialog(null, "Please select an order.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_applyDiscBtnActionPerformed

    private void pointsToRedeemTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsToRedeemTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointsToRedeemTxtActionPerformed

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        // TODO add your handling code here:
        //update()

        DefaultTableModel model = (DefaultTableModel) ordersTable.getModel();
        int selectedRowIndex = ordersTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            int orderId = (int) model.getValueAt(selectedRowIndex, 0);
            Transaction pendingTransaction = pos.getPendingTransactionByID(orderId);
            Double amtGiven = Double.valueOf(amtGivenTxt.getText());
            pendingTransaction.setAmtGiven(amtGiven);
            NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(Locale.US);
            changeTxt.setText(currencyFormatter.format(pendingTransaction.getChange()));
            updateTotal();
        } else {
            JOptionPane.showMessageDialog(null, "Please select an order.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void printReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReceiptBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ordersTable.getModel();
        int selectedRowIndex = ordersTable.getSelectedRow();

        if (selectedRowIndex != -1) {
            int orderId = (int) model.getValueAt(selectedRowIndex, 0);
            String message = String.format("Order Completion:\nProduct Name: %d\n", orderId);
            int option = JOptionPane.showConfirmDialog(this, message + "\nAre you sure you want to add this variant?", "Add New Variant", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                pos.printReceipt(orderId);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select an order.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_printReceiptBtnActionPerformed

    private void allPointsTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allPointsTxtMouseClicked
        // TODO add your handling code here:
        //Update
        pointsToRedeemTxt.setText(String.valueOf(pos.getCurrentCustomer().getPointsBalance()));
    }//GEN-LAST:event_allPointsTxtMouseClicked

    private void paymentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentFieldActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        int id = 1;
        String firstname = "John";
        String lastname = "Doe";
        String email = "johndoe@example.com";
        String contactNumber = "123-456-7890";
        String address = "123 Street, City, Country";
        String joinDate = "2024-01-01"; // Assuming join date is in yyyy-MM-dd format
        String role = "Employee";
        String department = "IT";
        float salary = 50000.0f; // Assuming salary is in dollars
        String password = "password123";

        User dummyUser = new User(id, firstname, lastname, email, contactNumber, address,
                joinDate, role, department, salary, password);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //fix
                new POSFrame(dummyUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton addOrderBtn;
    private javax.swing.JLabel allPointsTxt;
    private javax.swing.JTextPane amtGivenTxt;
    private javax.swing.JButton applyDiscBtn;
    private javax.swing.JLabel changeTxt;
    private javax.swing.JButton completeOrderBtn;
    private javax.swing.JTextPane customerIdTxt;
    private javax.swing.JLabel dateTime;
    private javax.swing.JTextField discCodeTxt;
    private javax.swing.JLabel employeeIdLabel;
    private javax.swing.JLabel greetLabel;
    private javax.swing.JTextField itemIDField;
    private javax.swing.JLabel itemItemLabel;
    private javax.swing.JTextField itemQuantityField;
    private javax.swing.JLabel itemQuantityLabel;
    private javax.swing.JTable itemsTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTable ordersTable;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JComboBox<String> paymentField;
    private javax.swing.JTextField pointsToRedeemTxt;
    private javax.swing.JButton printReceiptBtn;
    private javax.swing.JButton redeemPointsBtn;
    private javax.swing.JButton removeItemBtn;
    private javax.swing.JButton removeOrderBtn;
    private javax.swing.JLabel taxTxt;
    private javax.swing.JLabel totalTxt;
    private javax.swing.JLabel totalTxt1;
    // End of variables declaration//GEN-END:variables
}
